lights_manager:
  battery:
    charging_anim_step:
      type: double
      default_value: 0.1
      description: This parameter defines the minimum change in battery percentage required to trigger an update in the battery charging animation.
      validation: { gt<>: 0.0 }

    anim_period:
      critical:
        type: double
        default_value: 15.0
        description: Time in seconds to wait before repeating animation, indicating a critical Battery state.
        validation: { gt<>: 0.0 }

      low:
        type: double
        default_value: 30.0
        description: Time in seconds to wait before repeating the animation, indicating a low Battery state.
        validation: { gt<>: 0.0 }

    percent:
      window_len:
        type: int
        default_value: 6
        description: Moving average window length used to smooth out Battery percentage readings.
        validation: { gt<>: 0 }

      threshold:
        critical:
          type: double
          default_value: 0.1
          description: If the Battery percentage drops below this value, an animation indicating a critical Battery state will start being displayed.
          validation: { bounds<>: [0.0, 1.0] }

        low:
          type: double
          default_value: 0.4
          description: If the Battery percentage drops below this value, the animation indicating a low Battery state will start being displayed.
          validation: { bounds<>: [0.0, 1.0] }

  bt_project_path:
    type: string
    default_value: ""
    description: Path to a BehaviorTree project.
    validation: { not_empty<> }

  plugin_libs:
    type: string_array
    default_value: []
    description: List with names of plugins that are used in the BT project.

  ros_communication_timeout:
    availability:
      type: double
      default_value: 1.0
      description: Timeout in seconds to wait for a service/action while initializing BT node.
      validation: { gt<>: 0.0 }

    response:
      type: double
      default_value: 1.0
      description: Timeout in seconds to receive a service/action response after call.
      validation: { gt<>: 0.0 }

  ros_plugin_libs:
    type: string_array
    default_value: []
    description: List with names of ROS plugins that are used in a BT project.

  timer_frequency:
    type: double
    default_value: 10.0
    description: Frequency in Hz at which lights tree will be ticked.
    validation: { gt<>: 0.0 }
